package studying.java.constructor;

/**
 * Created by echaika on 02.07.2019
 */
class Foo {
    //default constructor will be generated by compiler
    Foo() {
        super();    // always first row
    }

    void print() {
        System.out.println("Foo default");
    }
}

class Bar {
    private String value;

    Bar(String value) {
        this.value = value;
    }

    //default constructor must be defined
    Bar() {
        super();
    }

    void print() {
        System.out.println("Bar default");
    }

    void printString() {
        System.out.println("Bar string - " + value);
    }
}

class Test {
    public static void main(String[] args) {
        new Bar().print();
        new Bar("test").printString();
        new Foo().print();
    }
}
